### Create Elasticsearch Sink Connector 
@baseurl=http://localhost:8083

POST {{baseurl}}/connectors HTTP/1.1
Content-Type: application/json

{
 "name": "simple-elasticsearch-connector",
 "config": {
   "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "connection.url": "http://elasticsearch:9200",
    "tasks.max": "1",
    "topics": "pg-football_players",
    "name": "simple-elasticsearch-connector",
    "type.name": "_doc",
    "value.converter.schemas.enable": "false",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url": "http://kafka-schema-registry:8081",
    "schema.ignore": "true",
    "key.ignore": "true"
 }
}

### Check Elastic Index Created Or Not
GET http://localhost:9200/pg-football_players/_search HTTP/1.1

###Get All Indexes
GET http://localhost:9200/_aliases?pretty=true HTTP/1.1

### Create Postgres JDBC Source Connector
POST {{baseurl}}/connectors HTTP/1.1
Content-Type: application/json

{
  "name": "postgres_product_listings",
  "config": 
    {
        "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
        "tasks.max": 1,
        "connection.url": "jdbc:postgresql://pg:5432/connectpoc",
        "connection.user": "root",
        "connection.password": "admin",
        "connection.attempts": "3",
        "table.whitelist": "football_players",
        "mode": "timestamp",
        "timestamp.column.name":"modified_at,created_at",
        "poll.interval.ms": "2000",
        "topic.prefix": "pg-"
    }
}

CREATE TABLE football_players (
  name VARCHAR ( 50 ) PRIMARY KEY,
  nationality VARCHAR ( 255 ) NOT NULL,
  is_retired BOOLEAN DEFAULT false,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  modified_at TIMESTAMP
  )

insert into football_players (name, nationality, is_retired) values ('Andrea Pirlo','Italian', true);
insert into football_players (name, nationality, is_retired) values ('Cristiano Ronaldo','Portuguese', false);
insert into football_players (name, nationality, is_retired) values ('Megan Rapinoe','American', true);

insert into football_players (name, nationality, is_retired) values ('Andrea Pirlo sad','Italian', true);
insert into football_players (name, nationality, is_retired) values ('Cristiano Ronaldo sdas','Portuguese', false);

insert into football_players (name, nationality, is_retired) values ('Andrea Pirlo ad','Italian', true);
insert into football_players (name, nationality, is_retired) values ('Cristiano Raldo sdas','Portuguese', false);
